#!/bin/sh
# Writes a OX820 MBR to mbr.bin

# Parameters for generation
STAGE1_PRIMARY_STARTSECTOR=34
STAGE1_SECONDARY_STARTSECTOR=57088
STAGE1_SECTOR_COUNT=128    # minus half for the rom bug

# Actual generation

STAGE1_PRIMARY_CHKSUM=$((STAGE1_PRIMARY_STARTSECTOR+STAGE1_SECTOR_COUNT))
STAGE1_SECONDARY_CHKSUM=$((STAGE1_SECONDARY_STARTSECTOR+STAGE1_SECTOR_COUNT))

dd if=/dev/zero of=mbr.bin bs=444 count=1

# Write 12 byte primary
VAL=$STAGE1_PRIMARY_CHKSUM
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 7))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 7))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >mbr.tmp

VAL=$STAGE1_PRIMARY_STARTSECTOR
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 7))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 7))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >>mbr.tmp

VAL=$STAGE1_SECTOR_COUNT
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 7))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 7))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >>mbr.tmp

dd if=mbr.tmp of=mbr.bin conv=notrunc seek=432 bs=1

# Write 12 byte secondary
VAL=$STAGE1_SECONDARY_CHKSUM
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 7))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 7))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >mbr.tmp

VAL=$STAGE1_SECONDARY_STARTSECTOR
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 3))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 3))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >>mbr.tmp

VAL=$STAGE1_SECTOR_COUNT
VAL_OCTAL0L=$((VAL & 7))
VAL_OCTAL0M=$(((VAL >> 3) & 7))
VAL_OCTAL0H=$(((VAL >> 6) & 3))

VAL_OCTAL1L=$(((VAL >> 8) & 7))
VAL_OCTAL1M=$(((VAL >> 11) & 7))
VAL_OCTAL1H=$(((VAL >> 14) & 3))

VAL_OCTAL2L=$(((VAL >> 16) & 7))
VAL_OCTAL2M=$(((VAL >> 19) & 7))
VAL_OCTAL2H=$(((VAL >> 22) & 3))

VAL_OCTAL3L=$(((VAL >> 24) & 7))
VAL_OCTAL3M=$(((VAL >> 27) & 7))
VAL_OCTAL3H=$(((VAL >> 30) & 3))

VAL_STRING="\0$VAL_OCTAL0H\0$VAL_OCTAL0M\0$VAL_OCTAL0L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL1H\0$VAL_OCTAL1M\0$VAL_OCTAL1L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL2H\0$VAL_OCTAL2M\0$VAL_OCTAL2L"
VAL_STRING="$VAL_STRING\0$VAL_OCTAL3H\0$VAL_OCTAL3M\0$VAL_OCTAL3L"
echo -en "$VAL_STRING" >>mbr.tmp

dd if=mbr.tmp of=mbr.bin conv=notrunc seek=420 bs=1

rm mbr.tmp

